Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,13 +3,35 @@ version: 2.1
 executors:
   docker-executor:
     docker:
-      - image: circleci/python:3.8
+      - image: python:3.8
 
 jobs:
   build-and-deploy:
     executor: docker-executor
     steps:
       - checkout
+
+      # Instalação do Docker
+      - setup_remote_docker:
+          version: 20.10.7
+
+      # Verificação da presença dos Dockerfiles
+      - run:
+          name: Check for Dockerfiles
+          command: |
+            ls -la
+            if [ ! -f frontend/Dockerfile ]; then
+              echo "Dockerfile not found in the frontend directory"
+              exit 1
+            fi
+            if [ ! -f backend/Dockerfile ]; then
+              echo "Dockerfile not found in the backend directory"
+              exit 1
+            fi
+            if [ ! -f service-node/Dockerfile ]; then
+              echo "Dockerfile not found in the service-node directory"
+              exit 1
+            fi
 
       # Remove containers e imagens existentes
       - run:
@@ -24,24 +46,27 @@ jobs:
             docker image rm -f service-node || true
             docker image rm -f db-postgres || true
 
-      # Build da imagem
+      # Build das imagens
       - run:
-          name: Build Docker image
+          name: Build frontend Docker image
           command: |
-            docker build -t myapp-image .
+            docker build -t frontend-image ./frontend
+      - run:
+          name: Build backend Docker image
+          command: |
+            docker build -t backend-image ./backend
+      - run:
+          name: Build service-node Docker image
+          command: |
+            docker build -t service-node-image ./service-node
 
-      # Criação e inicialização do container
+      # Criação e inicialização dos containers
       - run:
-          name: Create and start Docker container
+          name: Create and start Docker containers
           command: |
-            docker run -d --name myapp-container -p 80:80 myapp-image
-
-      # Envio de e-mail de notificação
-      - run:
-          name: Send notification email
-          command: |
-            sudo apt-get update && sudo apt-get install -y mailutils
-            echo "Build and Deploy Job: Success" | mail -s "CircleCI Job Status" your-email@example.com
+            docker run -d --name frontend-container -p 8080:80 frontend-image
+            docker run -d --name backend-container -p 8081:80 backend-image
+            docker run -d --name service-node-container -p 8082:80 service-node-image
 
 workflows:
   version: 2
